# Generated by Django 3.2 on 2023-02-14 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(default=True, max_length=14),
            preserve_default=False,
        ),
    ]
