# Generated by Django 3.2 on 2023-02-12 14:21

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tailor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('skill', models.CharField(choices=[('Tailor', 'Tailor'), ('Fashion Designer', 'Fashion Designer'), ('Tailor and Designer', 'Both')], default='Tailor', max_length=19)),
                ('business_name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=14)),
                ('experience', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(0)])),
                ('business_address', models.TextField()),
                ('bank', models.CharField(max_length=20)),
                ('account_number', models.CharField(max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.CharField(choices=[('0.5', '0.5'), ('1.0', '1.0'), ('1.5', '1.5'), ('2.0', '2.0'), ('2.5', '2.5'), ('3.0', '3.0'), ('3.5', '3.5'), ('4.0', '4.0'), ('4.5', '4.5'), ('5.0', '5.0')], default='5.0', max_length=3)),
                ('tailor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tailor_api.tailor')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
