# Generated by Django 3.2 on 2023-02-19 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tailor_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='duration',
            field=models.CharField(choices=[('7am - 8am', '7am - 8am'), ('10am - 11am', '10am - 11am'), ('1pm - 2pm', '1pm - 2pm'), ('4pm - 5pm', '4pm - 5pm'), ('7pm - 8pm', '7pm - 8pm'), ('9pm - 10pm', '9pm - 10pm')], default='7am - 8am', max_length=11),
        ),
    ]
