# Generated by Django 3.2 on 2023-03-02 00:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tailor_api', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RatingImage',
        ),
    ]
