# Generated by Django 3.2 on 2023-02-18 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tailor_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tailor',
            old_name='business_address',
            new_name='location',
        ),
    ]
