# Generated by Django 3.2 on 2023-02-13 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tailor_api', '0002_alter_task_delivered'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tailor',
            name='money_earned',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='tailor',
            name='pending_money',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='tailor',
            name='wallet_balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
    ]
