# Generated by Django 3.2 on 2023-02-28 12:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tailor_api', '0003_auto_20230228_0903'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='image',
        ),
        migrations.CreateModel(
            name='RatingImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='tailor_rating')),
                ('rating', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tailor_api.rating')),
            ],
        ),
    ]
