# Generated by Django 3.2 on 2023-03-01 12:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tailor_api', '0001_initial'),
        ('shop_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivered', models.BooleanField(default=False)),
                ('cart_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop_api.cartitem')),
                ('tailor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tailor_api.tailor')),
            ],
        ),
    ]
