# Generated by Django 3.2 on 2023-02-15 16:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop_api', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Length',
        ),
        migrations.AddField(
            model_name='cloth',
            name='category',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.DO_NOTHING, to='shop_api.category'),
            preserve_default=False,
        ),
    ]
