# Generated by Django 3.2 on 2023-03-01 07:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shop_api', '0002_auto_20230301_0838'),
    ]

    operations = [
        migrations.AddField(
            model_name='clothrating',
            name='date_created',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
