# Generated by Django 3.2 on 2023-02-15 16:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tailor_api', '0001_initial'),
        ('shop_api', '0002_auto_20230215_1713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cloth',
            name='uploader',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tailor_api.tailor'),
        ),
    ]
