# Generated by Django 3.2 on 2023-02-20 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_api', '0003_alter_card_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
