# Generated by Django 3.2 on 2023-02-15 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop_api', '0003_alter_cloth_uploader'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subcategory',
            name='category',
        ),
        migrations.AddField(
            model_name='cloth',
            name='sub_category',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.DO_NOTHING, to='shop_api.subcategory'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='name',
            field=models.CharField(max_length=20),
        ),
    ]
