# Generated by Django 3.2 on 2023-02-15 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_api', '0005_auto_20230215_1822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='color',
            name='name',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
