# Generated by Django 3.2 on 2023-02-15 17:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop_api', '0006_alter_color_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='cloth',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='shop_api.cloth'),
            preserve_default=False,
        ),
    ]
