# Generated by Django 3.2 on 2023-02-16 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_api', '0007_comment_cloth'),
    ]

    operations = [
        migrations.AddField(
            model_name='cloth',
            name='image',
            field=models.ImageField(default=True, upload_to='cloth/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='material',
            name='name',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.DeleteModel(
            name='ClothImage',
        ),
    ]
