# Generated by Django 3.2 on 2023-02-16 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_api', '0008_auto_20230216_0926'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cloth',
            name='material_type',
        ),
        migrations.AddField(
            model_name='cloth',
            name='material',
            field=models.CharField(default=True, max_length=30),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Material',
        ),
    ]
