# Generated by Django 3.2 on 2023-02-16 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_api', '0009_auto_20230216_1004'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cloth',
            name='available_colors',
        ),
        migrations.AddField(
            model_name='cloth',
            name='available_colors',
            field=models.CharField(default=True, max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cloth',
            name='sub_category',
            field=models.CharField(max_length=30),
        ),
        migrations.DeleteModel(
            name='Color',
        ),
        migrations.DeleteModel(
            name='SubCategory',
        ),
    ]
