# Generated by Django 3.2 on 2023-02-17 12:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tailor_api', '0001_initial'),
        ('shop_api', '0010_auto_20230216_1029'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('tailor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tailor_api.tailor')),
            ],
        ),
    ]
