# Generated by Django 3.2 on 2023-02-17 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop_api', '0011_transactionnotification'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionnotification',
            name='cloth',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='shop_api.cloth'),
            preserve_default=False,
        ),
    ]
