# Generated by Django 3.2 on 2023-02-18 06:52

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop_api', '0012_transactionnotification_cloth'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Like',
            new_name='ClothLike',
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-date_created']},
        ),
    ]
